### PR TITLE
fix: image CORS problem

### PR DESCRIPTION
**Pull request by niko-waker**

### CODE REVIEW

**Comment by ewwwgiddings** [comment]
Did this get merged? If so can the npm be updated?

**Comment by ewwwgiddings** [comment]
@niko-waker I still had some issues with what you used. Removing the 'same-origin' field worked for me.

`? window.fetch(url, {
    method: 'GET',
    mode: 'cors',
    cache: 'no-cache'
})`

**Comment by ewwwgiddings** [comment]
@bubkoo I think maybe having these as inputs/parameters would be helpful and solve the issue for everyone. This way we wouldn't need to go into the node modules.

**Comment by Allaoua9** [comment]
why this issue was closed ?

**Pull request closed without merging**
