### PR TITLE
Feature: Render scrolled children with scrolled content

### PR DESCRIPTION
**Pull request by cornedor**
### Description

Fixes https://github.com/bubkoo/html-to-image/issues/81

When rendering a child with its content scrolled, this feature will scroll the content in the final render.

### Motivation and Context

Screenshot from 2021-11-07 21-15-04

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [ ] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [x] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/bubkoo/html-to-image/blob/master/CONTRIBUTING.md) document.
- [x] I have added tests to cover my changes.
- [x] All new and existing tests passed.

### CODE REVIEW

**Comment by cornedor** [comment]
There is a small edge case for direct children with and without transforms. If one (or more) of the direct children has a transform, those elements will normally be rendered above other elements (without the z-index changing). However, since all the children in the scrolled node have a transform now, this might results in incorrect z-indices.

This edge case only happens on direct children in a scrolled node.

**Comment by anavvathi** [comment]
hello @cornedor  i have the same issue when i scroll to bottom and take screenshot its always taking scrolltop is this fix working for that if yes when are we moving to master.

**Comment by cornedor** [comment]
> hello @cornedor  i have the same issue when i scroll to bottom and take screenshot its always taking scrolltop is this fix working for that if yes when are we moving to master.

This only a fix for elements nested inside the element you are rendering. Scrolling the parent element is already fixed as far as I know.

**Comment by cornedor** [comment]
not-stale

**Comment by cornedor** [comment]
@bubkoo this is still relevant

**Comment by Haritaso** [comment]
@bubkoo Any chance getting this reviewed?

**Comment by shardulkul** [comment]
@bubkoo Can this PR be reviewed? Our team is looking for this fix for a long time.

**Comment by gdeggau** [comment]
@bubkoo could you review this one? I'm also facing this issue and we don't have any workaround :/

**Pull request closed without merging**
