### PR TITLE
fix: clone iframe nodes better

### PR DESCRIPTION
**Pull request by DustinBrett**
My previous PR adding iframe cloning was incomplete.

### Description

There were 2 specific reasons it didn't work:

- It doesn't work properly with `instanceof` across realms (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/instanceof#instanceof_and_multiple_realms)
- Child nodes for the `iframe` need to come from `contentDocument.body.childNodes`

To solve `instanceof` I've changed to comparing such as: `Object.getPrototypeOf(node).constructor.name === instance.name` where `instance` would be a prototype such as `HTMLImageElement`. This will also check recursively to see for example if something like `HTMLDivElement` also has `Element` in it's prototype chain and is therefore an instance of it.

Another solution suggested in MDN could be something like `myNode instanceof myNode.ownerDocument.defaultView.SVGElement`, but I had no luck (`Illegal invocation`) implementing this and I feel the method I have is a bit more ideal than just checking `tagName`'s.

### Motivation and Context

I want to fix this as I added iframe capture changes recently which caused this new issue to be visible.

### Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)
- [x] Enhancement (changes that improvement of current feature or performance)
- [ ] Refactoring (changes that neither fixes a bug nor adds a feature)
- [ ] Test Case (changes that add missing tests or correct existing tests)
- [ ] Code style optimization (changes that do not affect the meaning of the code)
- [ ] Docs (changes that only update documentation)
- [ ] Chore (changes that don't modify src or test files)

### Self Check before Merge

- [x] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have read the [**CONTRIBUTING**](https://github.com/bubkoo/html-to-image/blob/master/CONTRIBUTING.md) document.
- [ ] I have added tests to cover my changes.
- [ ] All new and existing tests passed.

### CODE REVIEW

**Comment by haodaking** [comment]
Can you take a look at the demo I wrote? The height of the iframe is missing, which is not as expected. thanks

https://codesandbox.io/s/sweet-knuth-3n57ws?file=/index.html

**Comment by DustinBrett** [comment]
> Can you take a look at the demo I wrote? The height of the iframe is missing, which is not as expected. thanks
> 
> https://codesandbox.io/s/sweet-knuth-3n57ws?file=/index.html

I'll take a look as I didn't have this specific issue.

**Comment by DustinBrett** [comment]
> Can you take a look at the demo I wrote? The height of the iframe is missing, which is not as expected. thanks
> 
> https://codesandbox.io/s/sweet-knuth-3n57ws?file=/index.html

To me this doesn't seem so bad but maybe I am missing something. It did clone the iframe and the image inside, but didn't respect the height of the iframe you are saying? I'm not sure I have a solution for this atm and also I am wondering if this issue is more related to my previous merged PR where iframe cloning began. Could you clarify the expected results and suggestions if you have any? I'm not sure if this PR needs to solve this specific issue unless the code changes caused it.

**Comment by haodaking** [comment]
> To me this doesn't seem so bad but maybe I am missing something. It did clone the iframe and the image inside, but didn't respect the height of the iframe you are saying? I'm not sure I have a solution for this atm and also I am wondering if this issue is more related to my previous merged PR where iframe cloning began. Could you clarify the expected results and suggestions if you have any? I'm not sure if this PR needs to solve this specific issue unless the code changes caused it.

image
image
image

The solution for #351 PR is to replace the iframe tag with a div tag, set the div as the style of the iframe, and then clone the content in the iframe body

**Comment by DustinBrett** [comment]
> > To me this doesn't seem so bad but maybe I am missing something. It did clone the iframe and the image inside, but didn't respect the height of the iframe you are saying? I'm not sure I have a solution for this atm and also I am wondering if this issue is more related to my previous merged PR where iframe cloning began. Could you clarify the expected results and suggestions if you have any? I'm not sure if this PR needs to solve this specific issue unless the code changes caused it.
> 
> image image image
> 
> The solution for #351 PR is to replace the `iframe` tag with a `div` tag, set the `div` as the style of the `iframe`, and then clone the content in the iframe body

Ok thanks for clarification. It would be good if the iframe could be cloned without it being a div, unless that is the ideal solution. I'll look into it more.

**Comment by DustinBrett** [comment]
> > To me this doesn't seem so bad but maybe I am missing something. It did clone the iframe and the image inside, but didn't respect the height of the iframe you are saying? I'm not sure I have a solution for this atm and also I am wondering if this issue is more related to my previous merged PR where iframe cloning began. Could you clarify the expected results and suggestions if you have any? I'm not sure if this PR needs to solve this specific issue unless the code changes caused it.
> 
> image image image
> 
> The solution for #351 PR is to replace the `iframe` tag with a `div` tag, set the `div` as the style of the `iframe`, and then clone the content in the iframe body

I've looked into this and it turns out that although #351 had a solution, it was not because of the div but because of changing the `iframe` (inline frame) to display as block. After looking at https://stackoverflow.com/a/28954135/5895982 I think it might make sense for this use case. I've applied that change in the latest commit and test on your codesandbox and it seemed to give the correct result now.

**Pull request merged**
