### PR TITLE
fix: 🐛 apply css styles to svg elements

### PR DESCRIPTION
**Pull request by ramadis**
## Description
Because of the way the library was handling SVGs, it was missing styles injected by CSS via the `class` attribute. This error caused SVG elements styled by CSS classes to appear differently than the browser. This fix basically removes custom processing for SVG tags and processes them as a standard `HTMLElement`, thus iterating over its children and copying applied styles.

I added a test as well to illustrate this situation. Compare these results:

Before | After
------------ | -------------
Screen Shot 2020-10-03 at 01 07 15 | Screen Shot 2020-10-03 at 01 06 46

Of course, I'm open to discussing these changes. Thank you for your amazing work on this library!

### CODE REVIEW

**Comment by ramadis** [comment]
Actually, I could use some help to debug _why_ this test is failing with Travis 🤷‍♂️. I invite you to test it locally and compare results.

**Comment by Danistc** [comment]
Hey! Really need this fix, any idea when it can be approved?

**Comment by bubkoo** [comment]
@ramadis @Danistc 

💖 Thanks for opening this pull request! 💖

I will take some time to investigate this PR, because I'am a part-time opensourcer, so please be patient and I will get back to you as soon as we can.

**Comment by bubkoo** [comment]
@ramadis @Danistc 

The test failed for default font style has little diff in local and CI's Chrome.

Local Chorme
image

CI Chrome
image

So I replace the `'Foreign Object'` text with a red block, and the spec passed.

image

**Pull request merged**
